// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTbP4dbCapQ0dnKA85c5gQk8QfUbgGnxk',
    appId: '1:221809095307:web:5b3cf03f47f528cf135a8e',
    messagingSenderId: '221809095307',
    projectId: 'amazingym-mo',
    authDomain: 'amazingym-mo.firebaseapp.com',
    storageBucket: 'amazingym-mo.firebasestorage.app',
    measurementId: 'G-G8ZHXK86ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADH6MtKuhseNu2cLDT7DzWDmzr6ufq6Ts',
    appId: '1:221809095307:android:b9db4fca07d20a8e135a8e',
    messagingSenderId: '221809095307',
    projectId: 'amazingym-mo',
    storageBucket: 'amazingym-mo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcSSKMm3ky8I3nhhaK8SCJ7Kbw1ze0j70',
    appId: '1:221809095307:ios:c7511e7a4932e3a2135a8e',
    messagingSenderId: '221809095307',
    projectId: 'amazingym-mo',
    storageBucket: 'amazingym-mo.firebasestorage.app',
    iosClientId: '221809095307-71a8rvte2e12uetllksrhaf5s75dmo1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazingymApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcSSKMm3ky8I3nhhaK8SCJ7Kbw1ze0j70',
    appId: '1:221809095307:ios:c7511e7a4932e3a2135a8e',
    messagingSenderId: '221809095307',
    projectId: 'amazingym-mo',
    storageBucket: 'amazingym-mo.firebasestorage.app',
    iosClientId: '221809095307-71a8rvte2e12uetllksrhaf5s75dmo1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazingymApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTbP4dbCapQ0dnKA85c5gQk8QfUbgGnxk',
    appId: '1:221809095307:web:bc04f8a8dfad0068135a8e',
    messagingSenderId: '221809095307',
    projectId: 'amazingym-mo',
    authDomain: 'amazingym-mo.firebaseapp.com',
    storageBucket: 'amazingym-mo.firebasestorage.app',
    measurementId: 'G-WW2CJSWJGX',
  );

}